In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [60]:
def activation(x):
    x = x.copy()
    x[x<0] = 0
    return x

In [61]:
eps = 0.2

In [91]:
mat = np.zeros((4,4))
mat = mat - eps + (np.eye(4)*(1+eps))

In [92]:
mat

array([[ 1. , -0.2, -0.2, -0.2],
       [-0.2,  1. , -0.2, -0.2],
       [-0.2, -0.2,  1. , -0.2],
       [-0.2, -0.2, -0.2,  1. ]])

In [98]:
x = np.array([0.2,0.4,0.6,0.8])

In [99]:
mat @ x

array([-0.16,  0.08,  0.32,  0.56])

In [100]:
activation(mat@x)

array([0.  , 0.08, 0.32, 0.56])

In [101]:
for i in range(10):
    x = activation(mat@x)

In [102]:
x

array([0.      , 0.      , 0.      , 0.420864])