In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Architecture of the network


The network that I am going to desing in order to get the appropriate outputs is like the following:

input layer --> <font color='green'>three</font> inputs with out activation function

hidden layers --> <font color='green'>one</font> hidden layer with <font color='green'>eight</font>  neurons in it. The activation function is set to be  <font color='green'> step funtion</font>

output --> <font color='green'>one</font> output with <font color='green'>step function</font> as the activation function



'<font color='purple'> Note that the threshold of the activation function is not necessarily zero</font>'

In [218]:
class Neural_Network():
    
    def __init__(self, input_shpe, hidden_shape, output_shape , th):
        self.input_shape = input_shape
        self.output_shape = output_shape
        self.hidden_shape = hidden_shape
        self.th = th
        
        self.w_list = self.Compile(input_shape, hidden_shape, output_shape)
        
        
    #### High Level Functions ####
    
    def Compile(self,input_shape, hidden_shape, output_shape):
        w_shapes = self.w_shape_build(input_shape, hidden_shape, output_shape)
        w_list = self.init_w_list(w_shapes)
        return w_list
    
    
    def feedforward(self,input_, w_list, th):
        hidden_raw = []
        hidden_activated = []
        x = input_
        for i in range(len(hidden_shape)):
            z = self.WxX(w_list[i],x)
            hidden_raw.append(z)
            hidden_activated.append(self.activation(z,th))
            x = z

        predict_raw = self.WxX(w_list[-1],hidden_activated[-1])
        predict_activated = self.activation(predict_raw,th)

        return hidden_raw, hidden_activated, predict_raw, predict_activated
    
    def predict(self, input_, w_list,th):
        result = []
        for x in input_:
            result.append(self.feedforward(x, w_list,th)[-1])
        return np.array(result).reshape(-1)
    
    
    #### Low Level Functions ###
    def w_shape_build(self,input_shape, hidden_shape, output_shape):
        total_shape = [input_shape] + hidden_shape + [output_shape]
        w_shapes= []
        for i in zip(total_shape[1:], total_shape[:-1]):
            w_shapes.append((i[0],i[1]+1))  # Note that the pluse one is for the bias term which is embedded into w matrix
        return w_shapes

    
    def init_w_list(self,w_shapes):
        w_list = []
        for w in w_shapes:
            w_list.append(np.random.random((w[0], w[1])))
        return w_list
    
    
    def WxX(self,w,x, activate = False):
        result = w @ self.one_adder(x).reshape((-1,1))

        if activate == True:
            return self.activate(result.reshape(-1))

        return result.reshape(-1)

    def activation(self,z_,th=1.3, same_as_init = False):
        
        if same_as_init == True:
            th = self.th
            
        z = z_.copy()
        z[z<th] = 0
        z[z>=th] = 1
        return z

    def one_adder(self,x):
        return np.array([1] + x.tolist())
    
            

## Defining the parameters of the model

In [299]:
input_shape = 3
output_shape = 1
hidden_shape = [8]
th = 4

## Creating the dataset

In [316]:
X = [(i//4,(i%4)//2,((i%4)%2)//1) for i in range(8)]
X = np.array(X)
X


array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [301]:
Y = [0,1,0,0,0,0,1,1]
Y = np.array(Y)

## Creating the model
This section will create the model and initialize the weights matrix with random numbers

In [302]:
model = Neural_Network(input_shape, hidden_shape, output_shape, th)

## Fine Tuning the Weights matrix

In [303]:
W = model.w_list.copy()

In [304]:
W

[array([[0.08664213, 0.72894515, 0.32590667, 0.55507009],
        [0.0907546 , 0.43368803, 0.41474378, 0.62107825],
        [0.12525472, 0.2629973 , 0.97138876, 0.24357252],
        [0.85345192, 0.76424185, 0.65246254, 0.73168287],
        [0.75541902, 0.11770481, 0.29968784, 0.88126495],
        [0.98702617, 0.74119478, 0.46462907, 0.62163536],
        [0.10695632, 0.73324012, 0.80564778, 0.90813546],
        [0.72667696, 0.74759824, 0.38610956, 0.27289131]]),
 array([[0.62950825, 0.47245994, 0.29865551, 0.30046157, 0.86821538,
         0.66413947, 0.97083089, 0.76812948, 0.01666012]])]

In [312]:
W[0][:,:] = 0
W[0][1,:] = np.array([0,-5,-5,5])
W[0][6,:] = np.array([0,3,3,0])
W[0][7,:] = np.array([0,2,2,1])
W[1][:,:] = 0
W[1][0,2] = 5
W[1][0,7] = 5
W[1][0,8] = 5


In [313]:
model.w_list = W
model.w_list

[array([[ 0.,  0.,  0.,  0.],
        [ 0., -5., -5.,  5.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  3.,  3.,  0.],
        [ 0.,  2.,  2.,  1.]]), array([[0., 0., 5., 0., 0., 0., 0., 5., 5.]])]

## Evaluating the prediction of the Network

In [314]:
model.predict(X, model.w_list,4)

array([0., 1., 0., 0., 0., 0., 1., 1.])

In [104]:
test = [12]
def Test(a):
    a[0] = 32
    return a
    

In [106]:
Test(test)

[32]

In [108]:
tes

[32]